services:
  php:
    ports:
      - 80:8080
    environment:
      - "PHP_DISPLAY_ERRORS=on"
  node:
    image: node:18-alpine
    restart: always
    tty: true
    ports:
      - "5173:5173"
    volumes:
      - ../:/var/www
    working_dir: /var/www
    networks:
      - net
networks:
  net:
    driver: bridge
